# v1.1.1 June 25, 2013 - CUSTOMISED
language: node_js
before_script: "./node_modules/.bin/cake test-setup"
script: "npm test"
node_js:
  - "0.10"
notifications:
  email:
    recipients:
      - hello@jimmyking.me
